apiVersion: v1
kind: Secret
metadata:
  name: openrouter-secret
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
type: Opaque
data:
  # Provide at deploy time:
  # helm upgrade todo-app todo-chatbot/ --set openrouter.apiKey="sk-or-v1-..."
  api-key: {{ .Values.openrouter.apiKey | b64enc | quote }}
